sonar.projectKey=production-devops-pipeline
sonar.projectName=Production DevOps Pipeline
sonar.projectVersion=1.0

sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8