spring.application.name=springboot-app
server.port=8081
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE