server:
  port: 8082

spring:
  application:
    name: production-devops-pipeline

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

info:
  app:
    name: Production DevOps Pipeline
    version: 1.0
    description: Enterprise DevOps Demo
    developer: Dandu Rama Siva Naga Raju