pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'cd app/springboot-app && mvn clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'cd app/springboot-app && mvn test'
            }
        }

    }

    post {

        always {
            archiveArtifacts artifacts: 'app/springboot-app/target/*.jar'
        }

        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed.'
        }

    }

}